swagger: "2.0"
info:
  version: "1.0.0"
  title: "mock-shop-api-server"
host: "mock-shop-api.herokuapp.com"
basePath: /
schemes:
- "https"
consumes:
- "application/json"
produces:
- "application/json"
paths:
  /users:
    get:
      description: "Get list of all users and admins in the system"
      summary: "Get Users"
      operationId: "GetUsers"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
          "200":
            description: "Success"
            schema:
              type: "object"
              properties:
                status:
                  type: "string"
                data:
                  type: "object"
          "401":
            description: "Error Bad Request"
            schema:
              type: "object"
              properties:
                status:
                  type: "string"
                data:
                  type: "object"
  /users/login:
    post:
      description: "Sign in with email and password to get token for authorization"
      summary: "Sign In"
      operationId: "SignIn"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "login details"
        in: "body"
        description: "login details"
        required: true
        schema:
          type: "object"
      # requestBody:
      #   content:
      #     "application/json"
      #       schema:
      #         properties:
      #           email:
      #             description: "Email address ussed for sign up"
      #             type: "string"
      #           password:
      #             description: "password"
      #             type: "string"
      #         required:
      #           - "email"
      #           - "password"
      responses:
          "200":
            description: "Success"
            schema:
              type: "object"
              properties:
                status:
                  type: "string"
                data:
                  type: "object"
          "401":
            description: "Error Bad Request"
            schema:
              type: "object"
              properties:
                status:
                  type: "string"
                data:
                  type: "object"